[tool.poetry]
name = "sshtools"
version = "2.19.14"
description = ""
authors = ["Tim Mees <tim.mees83@gmail.com>"]
homepage = "https://github.com/tim83/sshtools"
repository = "https://github.com/tim83/sshtools"
include = [
    'sshtools/devices.ini',
    'sshtools/home.ini',
    'sshtools/home-tim.ini',
    'sshtools/kot.ini',
    'sshtools/kot-tim.ini',
    'sshtools/zerotier.ini',
    'sshtools/exclude.txt',
    'sshtools/include.txt',
    'sshtools/limited.txt'
]

[tool.poetry.scripts]
getip = "sshtools.getip:run"
smount = "sshtools.smount:run"
sshin = "sshtools.sshin:run"
ssync = "sshtools.ssync:run"
wake-up = "sshtools.wakeup:run"

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
DateTime = "^4.3"
argparse = "^1.4.0"
configparser = "^5.0.2"
psutil = "^5.8.0"
fping = "^0.0.1-alpha.2"
timtools = {git = "https://github.com/tim83/timtools"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
